### ISSUE TITLE
Inconsistent function call / signature

### ISSUE THREAD

**Issue by jimmymathews** [CarlinLiao/cg-gnn#3]
@CarlinLiao mentioned that v0.1.2 (with #1) should be useable in a certain calling context (see SPT [#128](https://github.com/nadeemlab/SPT/issues/128)).

Possibly a `git add` or similar was missed? I'm seeing usage of `spt_to_dataframes` at [`run_all.py#L37`](https://github.com/CarlinLiao/cg-gnn/blob/d048d98ea33266f99493f4651ac273a94f33dcd2/cggnn/run_all.py#L37) that is inconsistent with the call signature in the function definition, [`spt_to_df.py#L191`](https://github.com/CarlinLiao/cg-gnn/blob/d048d98ea33266f99493f4651ac273a94f33dcd2/cggnn/spt_to_df.py#L191).

Old args:
```
analysis_study, measurement_study, specimen_study, host, dbname, user, password
```
New args:
```
study, host, dbname, user, password, output_name
```

**Comment by CarlinLiao** [comment]
My bad, I verified that the `a_spt_to_file.py` script was using the function args properly, but not `run_all.py`. This has been fixed on both the main branch and on PyPI.
