### ISSUE TITLE
rmtree incomplete deletion

### ISSUE THREAD

**Issue by jimmymathews** [CarlinLiao/cg-gnn#4]
I believe this last line in [`run_all.py`](https://github.com/CarlinLiao/cg-gnn/blob/d048d98ea33266f99493f4651ac273a94f33dcd2/cggnn/run_all.py#L79) is meant to delete temporary directory `tmp/`. It seems to delete the contents but leaves the directory itself.

**Comment by CarlinLiao** [comment]
I can't decide if this is intended functionality or not. The folder's just going to be created the next time you run the program, so I don't see any harm in leaving it there but empty, but it would be neater to get rid of it.
